# Generated by Django 4.2.7 on 2023-11-14 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_course_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userroles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(max_length=100)),
                ('role_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_unique', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_email', models.CharField(max_length=320)),
                ('user_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.userroles')),
            ],
        ),
    ]
