# Generated by Django 4.2.7 on 2023-11-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_users_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_id', models.IntegerField(blank=True, default=0, null=True)),
                ('course_id', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateField()),
            ],
        ),
    ]
