# Generated by Django 4.2.7 on 2023-11-20 06:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_alter_enrollment_candidate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_created',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='role_created',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=255)),
                ('candidates', models.TextField()),
                ('start_date', models.DateField(default=datetime.datetime.today)),
                ('date_created', models.DateField(default=datetime.datetime.today)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.course')),
            ],
        ),
    ]
