# Generated by Django 4.1 on 2023-12-28 14:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_alter_course_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.TextField()),
                ('editable', models.BooleanField(default=False)),
                ('payment_reference', models.ImageField(blank=True, null=True, upload_to='payment_references/')),
                ('date_created', models.DateField(default=datetime.datetime.today)),
                ('batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.batch')),
                ('candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.enrollment')),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.course')),
            ],
        ),
    ]
