# Generated by Django 4.1 on 2024-01-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='candidate_id',
            new_name='candidate_enrollment',
        ),
    ]
