# Generated by Django 4.1 on 2024-01-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_rename_candidate_id_payments_candidate_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='editable',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payment_reference',
        ),
    ]
