# Generated by Django 4.1 on 2024-01-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_remove_payments_editable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='candidate_enrollment',
            new_name='candidate_id',
        ),
    ]
