# Generated by Django 4.1 on 2024-01-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_rename_candidate_enrollment_payments_candidate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_reference',
            field=models.ImageField(blank=True, null=True, upload_to='payment_references/'),
        ),
    ]
