# Generated by Django 4.1 on 2024-01-06 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_payments_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='candidate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.users'),
        ),
    ]
