# Generated by Django 4.1 on 2024-01-06 20:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0013_alter_payments_candidate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField()),
                ('comany_addr', models.TextField()),
                ('company_poc', models.TextField()),
                ('contact_no', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('interview_date', models.DateField()),
                ('date_created', models.DateField(default=datetime.datetime.today)),
                ('candidateid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.users')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.company')),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.course')),
            ],
        ),
    ]
